### ISSUE TITLE
Missing return statement on error

### ISSUE THREAD

**Issue by fooock** [onesaitplatform/onesaitplatform-cloud#1]
Maybe you need to put a return statement after line 50 to break method execution.

https://github.com/onesaitplatform/onesaitplatform-cloud/blob/85678e668205a7ee724bbdb53fe796644c032ffa/sources/libraries/digital-twin/digital-twin-library/src/main/java/com/minsait/onesait/platform/digitaltwin/action/controller/ActionRestController.java#L50

Possible fix:

```java
if (!actionJSON.has("name")) {
    log.error("Invalid JSON action, \"name\" property is required");
    return;
}
```
Using this approach, you fail fast and avoid executing unused code? Without this return, you can send empty or null `actionName` in line [61](https://github.com/onesaitplatform/onesaitplatform-cloud/blob/85678e668205a7ee724bbdb53fe796644c032ffa/sources/libraries/digital-twin/digital-twin-library/src/main/java/com/minsait/onesait/platform/digitaltwin/action/controller/ActionRestController.java#L61) and line [64](https://github.com/onesaitplatform/onesaitplatform-cloud/blob/85678e668205a7ee724bbdb53fe796644c032ffa/sources/libraries/digital-twin/digital-twin-library/src/main/java/com/minsait/onesait/platform/digitaltwin/action/controller/ActionRestController.java#L64)

Cheers ✌️

**Comment by ebustosm** [comment]
Hi @fooock , 

We are launching a new version of the platform in the following days where it is corrected.
We agree with your solution, please, make a pull request with your solution and we will accept it.
Thank you for contribute to the project.

Regards
Onesait Platform Team
