### ISSUE TITLE
NodeRed Node Dynamic Query results in Class Cast Exception

### ISSUE THREAD

**Issue by UncleDinoso** [onesaitplatform/onesaitplatform-cloud#130]
Hy, i want to execute a simple update statement on a virtual entity, located in a postgresdb:

`msg.ontology = 'airquality_observed_dynamicdata_hl';
msg.queryType = 'SQL';
msg.query = 'update airquality_observed_dynamicdata_hl set co2value = 0;';
return msg;`

The debug output of the Dynamic Query Node is:
`"Error executing query. Ontology=airquality_observed_dynamicdata_hl, QueryType =SQL, Query = update airquality_observed_dynamicdata_hl set co2value = 0;. Cause = com.minsait.onesait.platform.persistence.exceptions.DBPersistenceException: java.lang.ClassCastException."`

Select statements works flawful and with the query tool, i can execute the update statement without trouble, so i think, its a node-red node problem.

Schema of entity:
![image](https://github.com/onesaitplatform/onesaitplatform-cloud/assets/97948610/ec13ab06-0eb2-4e61-a477-e627b146876d)

**Comment by renetashi** [comment]
Hi @UncleDinoso, we are looking into it.

We'll try to replicate the behaivour and came you back to you with the result.

**Comment by renetashi** [comment]
Hi @UncleDinoso,

The issue has been fixed in the 6.0.0-CE version.

**Comment by UncleDinoso** [comment]
Thank you for your reply and fixing the issue :-)
