### ISSUE TITLE
Flow Engine ConfigDB threshold Error

### ISSUE THREAD

**Issue by UncleDinoso** [onesaitplatform/onesaitplatform-cloud#136]
Cheers,

in FlowEngine logs, i got following errors on 5.3.0-CE:

`NodeRedDomainSyncMonitorImpl[0;39m - Error precessing ConfigDB thresholds. Current values will be ignored.`

At the moment, i cant see any problems with this, but the log is full of the entries which will be logged in 30 sec cycle.

I restarted flowengine an configdb, but error persists.

**Comment by renetashi** [comment]
Hi @UncleDinoso,

We have replicated this behaviour, and it's not a critical error. In fact, it should not be displayed in the log as an error, as it is non blocking, meaning, everything keeps on running and you can ignore it.

This will be fixed in the upcoming version 6.0.0-CE coming out in July.

**Comment by UncleDinoso** [comment]
Thank you for your reply and fixing the issue :-)
