### ISSUE TITLE
Import from REST-Entites not working

### ISSUE THREAD

**Issue by UncleDinoso** [onesaitplatform/onesaitplatform-cloud#138]
Hy,

i imported an REST-Entity with bundle-load on ControlPanel. The Entity is created in table ontology, but in the ontology_rest* tables are no entries and the entity can not be used.

table ontology:
![image](https://github.com/onesaitplatform/onesaitplatform-cloud/assets/97948610/3d6469d8-9c2f-45a4-b2e8-ea7acec2844f)

table ontolgy_rest:
![image](https://github.com/onesaitplatform/onesaitplatform-cloud/assets/97948610/55f37f63-b21e-4b51-8955-8f828ec3c979)

Edit the entity in Control-Panel show New Entity Wizard and after choose "Creation from REST API" results in Error 500

**Comment by renetashi** [comment]
Hi @UncleDinoso,

Can you give us more detail?
In order to be able to replicate the potential issue, we need a detailed step by step guide of what you did, including the bundle loaded and/or the Rest-entity imported.

**Comment by UncleDinoso** [comment]
Cheers,

i build an bundle for you to debug the behavior.
![image](https://github.com/onesaitplatform/onesaitplatform-cloud/assets/97948610/2f30218e-f630-45c1-879f-89b7a5aafe39)
[KWL_REST_Ontology.zip](https://github.com/user-attachments/files/15913017/KWL_REST_Ontology.zip)

As you can see, in the bundle are no information for the ontology_rest* tables in configdb.

Here are the REST-Operations for the Entity:

![image](https://github.com/onesaitplatform/onesaitplatform-cloud/assets/97948610/9e787315-54f8-4bcd-b604-aa1f76c804c5)

So i think its an missing export form this settings.

**Comment by UncleDinoso** [comment]
Dear onesait-team,

are there any informations about this issue? Do you need more informations?

Thanks in advance!

**Comment by renetashi** [comment]
Hi @UncleDinoso,

I have been able to replicate the behaviour, and we have detected the cause.
We are now working so this issue will be fixed for the upcaming version.

**Comment by UncleDinoso** [comment]
Thank you for your reply and fixing the issue :-)
