### ISSUE TITLE
API Manager ControlPanel Error Query Custom

### ISSUE THREAD

**Issue by UncleDinoso** [onesaitplatform/onesaitplatform-cloud#145]
Cheers,

i encounter a problem in controlpanel version CE-6.0.0.

If i want to add an CustomQuery for an API, nothing happens and the browser console is showing error:

![grafik](https://github.com/user-attachments/assets/60c86f8c-8261-4061-9cfb-76f9a00a6e02)

When i importing a API with custom Query from CE-5.3.0 version, the custom query is stored successful and is shown in ui:

![grafik](https://github.com/user-attachments/assets/7892e297-5df8-471e-bd3c-47e7405a8724)

So i think its an fronted bug in controlpanelservice. 

Thank you!

Best regards,
UncleDinoso

**Comment by lmgracia** [comment]
Hello UncleDinoso,
We have resolved this issue and it will be fixed in the next CE version which will be released on 11 October.

Regards

**Comment by UncleDinoso** [comment]
Thank you :-)
