### ISSUE TITLE
Public Dashboard can not open without Authentification

### ISSUE THREAD

**Issue by UncleDinoso** [onesaitplatform/onesaitplatform-cloud#146]
Cheers,

in CE-6.0.0 i found a bug, that public Dashboards URL is redirected to keycloak.

So the can not be open without authenticate as user in platform.

We use keycloak and keycloakmanager is running.

Best wishes

UncleDinoso

**Comment by lmgracia** [comment]
Hi @UncleDinoso 
We have just verified the bug, in the next CD release it will be fixed.

**Comment by UncleDinoso** [comment]
is fixed
