### ISSUE TITLE
Dashboardengineservice restarts on CE-6.1.0

### ISSUE THREAD

**Issue by UncleDinoso** [onesaitplatform/onesaitplatform-cloud#147]
Cheers,

i updated a CE-6.0.0 Instance with CE-6.1.0.

Dashboardengineservice restarts every time with error:
`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'socketBrokerConfig': Unsatisfied dependency expressed through field 'webSocketMessageBrokerStats': Error creating bean with name 'webSocketMessageBrokerStats' defined in class path resource [org/springframework/web/socket/config/annotation/DelegatingWebSocketMessageBrokerConfiguration.class]: Unsatisfied dependency expressed through method 'webSocketMessageBrokerStats' parameter 0: Error creating bean with name 'stompBrokerRelayMessageHandler' defined in class path resource [org/springframework/web/socket/config/annotation/DelegatingWebSocketMessageBrokerConfiguration.class]: Unsatisfied dependency expressed through method 'stompBrokerRelayMessageHandler' parameter 4: Error creating bean with name 'userRegistryMessageHandler' defined in class path resource [org/springframework/web/socket/config/annotation/DelegatingWebSocketMessageBrokerConfiguration.class]: Unsatisfied dependency expressed through method 'userRegistryMessageHandler' parameter 3: Error creating bean with name 'brokerMessagingTemplate': Requested bean is currently in creation: Is there an unresolvable circular reference?`

Is there a bug in dashboardengineservice or a configuration-failure?

**Comment by prubiog** [comment]
Hi,
when have you pulled the image? We haven't finished the generation process of 6.1.0-ce version until a few hours ago, maybe you have pulled a corrupt image. Can you try again? 

We checked every module in our kubernetes cluster this morning and they were starting and working fine.

Best Regards,
Onesait Platform Support Team

**Comment by UncleDinoso** [comment]
Hi prubiog, i repulled the image and now it runs :-)
Thank you

Best regards
UncleDinoso
