### ISSUE TITLE
JavaScript code not executing in Paginated Table options button - Uncaught SyntaxError

### ISSUE THREAD

**Issue by SEWillmann** [onesaitplatform/onesaitplatform-cloud#150]
Hi, 
as I attempt to add JavaScript functionality to the on Click event of the options button of a Paginated Table and Paginated Table from Server Component, the code entered into the textbox is not properly registered or syntax-highlighted as functional code. When attempting to test and execute the code, I receive the following error in the console:

![Bildschirmfoto vom 2024-12-17 10-33-23](https://github.com/user-attachments/assets/78f850bf-67f3-4d59-964b-0fb38c94fa00)

Steps to Reproduce

    Open Forms and use a Paginated Table from Server Component
    Go to the table options buttons
    Select one and enter JavaScript code into the provided textbox
    Save the changes, and click the option Button
    Observe the error message in the console

Expected Behavior
     The entered JavaScript code should be properly registered and executed without syntax errors.

Actual Behavior
     The entered JavaScript code is not recognized as valid code, and attempting to execute it results in a syntax error.

Best regards 
SEWillmann

**Comment by prubiog** [comment]
Hello, first of all, thank you for using the platform :)

The javascript code you are using is probably too complex for the place where it is added, which is in the onclick="" of the button of each row, try to simplify it.
 
Best Regards,
Onesait Platform Support Team

**Comment by SEWillmann** [comment]
Dear Onesait Platform Support Team,

thanks for your reply. I tried it with a **console.log("");** . I cant imagine that it can be any simpler as that :) 

Best regards
SEWillmann
